### ISSUE TITLE
Strings \ Trim

### ISSUE THREAD

**Issue by joseph-walker** [joseph-walker/vector#28]
trim :: String -> String
Returns a string with leading and trailing whitespace removed

**Comment by loganhenson** [comment]
@joseph-walker trim is implemented, but do we want to go ahead and implement:

`trim :: String -> String -> String`
`ltrim :: String -> String -> String`
`rtrim :: String -> String -> String`

?

**Comment by joseph-walker** [comment]
I would say go ahead and split them out, then just define trim as the composition of ltrim and rtrim.

**Comment by loganhenson** [comment]
ended up doing chomp/lchomp/rchomp and leaving trim as just the whitespace utility based on..things.
