### ISSUE TITLE
Collections Parity

### ISSUE THREAD

**Issue by loganhenson** [joseph-walker/vector#56]
- [ ] <strike>all</strike> (This is collection specific)
- [x] avg
- [ ] chunk
- [x] collapse
- [ ] combine
- [x] contains
- [x] count
- [ ] diff
- [ ] diffKeys
- [ ] <strike>each</strike> (Literally the only use for this function is creating side effects)
- [ ] every
- [ ] except
- [x] filter
- [ ] first
- [x] flatMap
- [x] flatten
- [ ] flip
- [ ] forget
- [ ] forPage
- [ ] get
- [ ] groupBy
- [ ] has
- [ ] implode
- [ ] intersect
- [ ] isEmpty
- [ ] keyBy
- [x] keys
- [ ] last
- [x] map
- [x] max
- [ ] merge
- [x] min
- [ ] only
- [ ] pluck
- [ ] pop
- [ ] prepend
- [ ] pull
- [ ] push
- [ ] put
- [ ] random
- [x] reduce
- [ ] <strike>reject</strike> (This is a fluff method, it's just the inverse of filter)
- [x] reverse
- [ ] search
- [ ] shift
- [ ] shuffle
- [ ] slice
- [ ] sort
- [ ] sortBy
- [ ] sortByDesc
- [ ] splice
- [x] sum
- [x] take
- [ ] toArray
- [ ] toJson
- [ ] <strike>transform</strike> (Vector is not in the business of mutation)
- [ ] union
- [ ] unique
- [x] values
- [ ] where
- [ ] whereStrict
- [ ] whereIn
- [ ] whereInLoose
- [x] zip

**Comment by joseph-walker** [comment]
Transform mutates the original array. We're not implementing that one. Also a lot of these can be implemented by composing a couple existing functions -- do we just want to provide wrappers for those so people don't have to do it themselves?

**Comment by loganhenson** [comment]
Wrappers yes. Can we put wont implement in the list as strikes and a comment on original post?

**Comment by loganhenson** [comment]
no longer a goal
