### ISSUE TITLE
Using soft-reserved words for modules.

### ISSUE THREAD

**Issue by joseph-walker** [joseph-walker/vector#59]
We're using a soft-reserved word for the `Object` module, so let's use this as an opportunity to make the other module names consistent while we're making a BC change.

Object -> Objects
ArrayList -> Arrays
Strings (ok)

**Comment by joseph-walker** [comment]
http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by loganhenson** [comment]
slated in https://github.com/joseph-walker/vector/blob/master/changelog.md
